#!/bin/bash
# /etc/init.d/mate-speed-daemon

### BEGIN INIT INFO
# Provides:          mate-speed-daemon
# Required-Start:    $syslog $named $network $time
# Required-Stop:     $syslog $named $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mate-speed.sm.de deamon
# Description:       The daemon for the codespeed instance for the SOM project
### END INIT INFO

DAEMON_PATH="/home/www-data/mate-speed"

DAEMON=$DAEMON_PATH/speed_unicorn.sh
DAEMONOPTS=""

NAME=mate-speed
DESC="The daemon for the codespeed instance for the Mate project"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

. $(dirname "$0")/daemon.inc
