#!/bin/bash
# /etc/init.d/somns-speed-daemon

### BEGIN INIT INFO
# Provides:          somns-speed-daemon
# Required-Start:    $syslog $named $network $time
# Required-Stop:     $syslog $named $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: somns-speed.sm.de deamon
# Description:       The daemon for the codespeed instance for the SOMns project
### END INIT INFO

DAEMON_PATH="/home/www-data/somns-speed"

DAEMON=$DAEMON_PATH/speed_unicorn.sh
DAEMONOPTS=""

NAME=somns-speed
DESC="The daemon for the codespeed instance for the SOMns project"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

. $(dirname "$0")/daemon.inc
